### ISSUE TITLE
Geographical animation: spready by date and i want to add TimeSlider down the map for prediction for covid 19 pls answer

### ISSUE THREAD

**Issue by sheetalrajbhar** [docker-library/faq#20]
`
from folium.plugins import Time Slider Choropleth 

    country_df['last_update'] = country_df['last_update'].apply(str)
    country_df['Confirmed_log1p'] = np.log1p(country_df['confirmed'])
    country_df['deaths_log1p'] = np.log1p(country_df['deaths'])
    country_df['recovered_log1p'] = np.log1p(country_df['recovered'])
    country_df['active_log1p'] = np.log1p(country_df['active'])

    fig = px.scatter_geo(country_df, locations="country", locationmode='country names',
    color="confirmed", size='confirmed', hover_name="country", 
     hover_data=['confirmed', 'deaths','recovered','active'],
    range_color= [0, country_df['confirmed'].max()], 
    projection="natural earth", animation_frame="last_update", 
    title='COVID-19: confirmed, deaths, active and recovered cases spread Over Time', color_continuous_scale="portland")
    fig.update(layout_coloraxis_showscale=False)
    fig.show()

![newplot (2)](https://user-images.githubusercontent.com/44339198/112191413-ff525400-8c2b-11eb-8ba6-61d9c5206de6.png)
`

**Comment by wglambert** [comment]
This seems to be filed this in the wrong place, this is the [FAQ](https://github.com/docker-library/faq#frequently-asked-questions) for the Docker [Official Images](https://docs.docker.com/docker-hub/official_images/)
