### ISSUE TITLE
A question about updating the dependencies by the commands on Dockerfile

### ISSUE THREAD

**Issue by smgtkn** [docker-library/faq#36]
Hello, 

Thanks for maintaining Docker official images! I have the following question;

To my understanding, for or the sake of repeatability, a Dockerfile should install the same version of software every time it is rebuilt.  However, it can install updated versions of the dependencies by issuing commands such as 'apt-get update' etc. I was wondering if there is any official image that updates its dependencies by leveraging these type of commands, without having an updated Dockerfile and a new library definition file commit, just by being rebuilt from the same Dockerfile.  More specifically, do you ever rebuild repositories from the same Dockerfile (and context) without any update on them or on the metadata of CI/CD pipeline, or can we say that there needs to be a new library definition file commited for an image to be build (except from base image triggered rebuilds)?

**Comment by tianon** [comment]
I'm not sure exactly what you mean -- there are a number of reasons we might rebuild a given `Dockerfile`, and any one of them might install updated dependencies.  What we try to ensure is that for a given tag such as `bash:5.2.26` is that it either builds successfully and correctly contains Bash 5.2.26, or fails to build (if doing so is not possible, such as in the case of a package repository that does not keep a record of historical packages).  It should never successfully build the `Dockerfile` for that tag and have the end result accidentally contain Bash 5.2.27 instead, for example.
