### ISSUE TITLE
Is there an Open Source requirement?

### ISSUE THREAD

**Issue by murphpdx** [docker-library/faq#9]
It looks like the majority, if not all, of docker images in the library are open source. Am I disqualified from submitting an image if the software contained is closed source? Our organization is the owner of the software we would like to submit. 

A related question: If the software is open source but it's used as in conjunction with a subscription, would it be ok to submit an image?

**Comment by wglambert** [comment]
https://github.com/docker-library/mongo/issues/324#issuecomment-456308160
>There are other official images which ship proprietary code, yes (we only officially require that the image source code itself in the form of a Dockerfile + context be available in some form we can consume to build -- otherwise we wouldn't be able to build/push an image).

https://github.com/docker-library/mongo/issues/324#issuecomment-456166637
>It's typically been our approach that complying with binary distribution and use licenses is definitely the purview of our users (see, for example, the common boilerplate we add to every image description: https://github.com/docker-library/docs/blob/51aabaab0c571d39e2f22326b940fc234b97b42d/.template-helpers/license-common.md).

**Comment by yosifkit** [comment]
> If the software is open source but it's used as in conjunction with a subscription, would it be ok to submit an image?

My initial reaction is that it doesn't sound like the image would be "generally useful".  See also https://github.com/docker-library/official-images/pull/4800#issuecomment-422210085 and https://docs.docker.com/docker-hub/official_images/#creating-an-official-image

We do have images that require a license, like [`php-zendserver`](https://hub.docker.com/_/php-zendserver) (it does come with a trial license built in).

**Comment by tianon** [comment]
There are historical examples which are not (it wouldn't be a successful policy without some exceptions, right? :sweat_smile:), but the intent of https://github.com/docker-library/official-images/pull/11473 and related changes is that they _should_ be, yes, and that's what we plan to enforce going forward. :+1:

(Sorry it took us so long to come back around and wrap this up!)
